### ISSUE TITLE
使用 HSDB 查看Spring AOP产生的代理类

### ISSUE THREAD

**Issue by yf2008** [yf2008/duty-machine#196]
https://juejin.im/post/5e521a8bf265da573a01f0e9

**Comment by yf2008** [comment]
使用 HSDB 查看Spring AOP产生的代理类 by 2020年02月23日阅读 25
------
<article itemscope="itemscope" itemtype="http://schema.org/Article" data-v-fa2339b8><meta itemprop="url" content="https://juejin.im/post/5e521a8bf265da573a01f0e9"><meta itemprop="headline" content="使用 HSDB 查看Spring AOP产生的代理类"><meta itemprop="keywords" content="Java"><meta itemprop="datePublished" content="2020-02-23T06:34:16.334Z"><meta itemprop="image" content="https://b-gold-cdn.xitu.io/icon/icon-128.png"><div itemprop="author" itemscope="itemscope" itemtype="http://schema.org/Person"><meta itemprop="name" content="李师傅"><meta itemprop="url" content="https://juejin.im/user/5960b84d51882568d00a9f33"></div><div itemprop="publisher" itemscope="itemscope" itemtype="http://schema.org/Organization"><meta itemprop="name" content="掘金"><div itemprop="logo" itemscope="itemscope" itemtype="https://schema.org/ImageObject"><meta itemprop="url" content="https://b-gold-cdn.xitu.io/icon/icon-white-180.png"><meta itemprop="width" content="180"><meta itemprop="height" content="180"></div></div><div data-v-fa2339b8><a href="/post/5e521a8bf265da573a01f0e9" target="_blank" rel="" data-v-fa2339b8><div data-src="https://b-gold-cdn.xitu.io/v3/static/img/default-avatar.e30559a.svg" data-v-95ddf8f6 data-v-39db9419 data-v-fa2339b8></div></a><div data-v-fa2339b8><a href="/post/5e521a8bf265da573a01f0e9" target="_blank" rel="" data-v-263f3a32 data-v-fa2339b8></a><div data-v-fa2339b8><time datetime="2020-02-23T06:34:16.334Z" title="Sun Feb 23 2020 14:34:16 GMT+0800 (China Standard Time)" data-v-fa2339b8>2020年02月23日</time><span data-v-fa2339b8>阅读 25</span></div></div></div><h1 data-v-fa2339b8>使用 HSDB 查看Spring AOP产生的代理类</h1><div data-id="5e521ce86fb9a07ca601a387" itemprop="articleBody" data-v-fa2339b8><h2 data-id="heading-0">前言</h2><p>因为aop产生的代理类是运行期的，所以没法直接查看，需要使用HotSpot Debugger工具才能查看</p><h2 data-id="heading-1">使用步骤</h2><p>1. 启动java程序，保持运行状态。获取程序pid</p><p>2.使用</p><p></p><p></p><p></p><p></p><pre><code lang="bash">java -classpath <span>"<span>$JAVA_HOME</span>/lib/sa-jdi.jar"</span> sun.jvm.hotspot.HSDBjava -classpath <span>"C:\Program Files\Java\jdk1.8.0_221\lib\sa-jdi.jar"</span> sun.jvm.hotspot.HSDB<span>复制代码</span></code></pre><p>命令启动hsdb</p><p>3.HSDB: File-----&gt;Attach to HotSpot Process-----&gt;填入pid</p><p>4.HSDB: Tools-----&gt;Class Browser</p><p>5.可以根据类的名字进行筛选，然后生成class字节码</p><h2 data-id="heading-2">注意事项</h2><p>1.拿到字节码后反编译(丢入 idea自动反编译)即可查看代码</p><p>2.使用步骤2中如果发生如下错误</p><p></p><p></p><p></p><p></p><pre><code lang="bash">Exception <span>in</span> thread <span>"Thread-1"</span> java.lang.UnsatisfiedLinkError: Can<span>'t load library: C:\Program Files\Java\jre1.8.0_231\bin\sawindbg.dllat java.lang.ClassLoader.loadLibrary(Unknown Source)at java.lang.Runtime.load0(Unknown Source)at java.lang.System.load(Unknown Source)at sun.jvm.hotspot.debugger.windbg.WindbgDebuggerLocal.&lt;clinit&gt;(WindbgDebuggerLocal.java:661)at sun.jvm.hotspot.HotSpotAgent.setupDebuggerWin32(HotSpotAgent.java:567)at sun.jvm.hotspot.HotSpotAgent.setupDebugger(HotSpotAgent.java:335)at sun.jvm.hotspot.HotSpotAgent.go(HotSpotAgent.java:304)at sun.jvm.hotspot.HotSpotAgent.attach(HotSpotAgent.java:140)at sun.jvm.hotspot.HSDB.attach(HSDB.java:1184)at sun.jvm.hotspot.HSDB.access$1700(HSDB.java:53)at sun.jvm.hotspot.HSDB$25$1.run(HSDB.java:456)at sun.jvm.hotspot.utilities.WorkerThread$MainLoop.run(WorkerThread.java:66)at java.lang.Thread.run(Unknown Source)</span><span>复制代码</span></code></pre><p>就找一下<span>sawindbg.dll然后放到</span><span>C:\Program Files\Java\jre1.8.0_231\bin\目录即可</span></p><p><br></p></div></article>
