### ISSUE TITLE
解析一下阿里出品的泰山版Java开发手册

### ISSUE THREAD

**Issue by yf2008** [yf2008/duty-machine#24]
https://juejin.im/post/5ea632656fb9a03c4237b95e

**Comment by yf2008** [comment]
解析一下阿里出品的泰山版Java开发手册 by 2020年04月27日阅读 2477
------
<article itemscope="itemscope" itemtype="http://schema.org/Article" data-v-7407bc26><meta itemprop="url" content="https://juejin.im/post/5ea632656fb9a03c4237b95e"><meta itemprop="headline" content="解析一下阿里出品的泰山版Java开发手册"><meta itemprop="keywords" content="Java"><meta itemprop="datePublished" content="2020-04-27T01:18:28.855Z"><meta itemprop="image" content="https://b-gold-cdn.xitu.io/icon/icon-128.png"><div itemprop="author" itemscope="itemscope" itemtype="http://schema.org/Person"><meta itemprop="name" content="沉默王二"><meta itemprop="url" content="https://juejin.im/user/5bd7fb9ce51d45219836421e"></div><div itemprop="publisher" itemscope="itemscope" itemtype="http://schema.org/Organization"><meta itemprop="name" content="掘金"><div itemprop="logo" itemscope="itemscope" itemtype="https://schema.org/ImageObject"><meta itemprop="url" content="https://b-gold-cdn.xitu.io/icon/icon-white-180.png"><meta itemprop="width" content="180"><meta itemprop="height" content="180"></div></div><div data-v-7407bc26><a href="/post/5ea632656fb9a03c4237b95e" target="_blank" rel="" data-v-7407bc26><div data-src="https://b-gold-cdn.xitu.io/v3/static/img/default-avatar.e30559a.svg" data-v-292b3648 data-v-11331c20 data-v-7407bc26></div></a><div data-v-7407bc26><a href="/post/5ea632656fb9a03c4237b95e" target="_blank" rel="" data-v-44e95489 data-v-7407bc26></a><div data-v-7407bc26><time datetime="2020-04-27T01:18:28.855Z" title="Mon Apr 27 2020 09:18:28 GMT+0800 (China Standard Time)" data-v-7407bc26>2020年04月27日</time><span data-v-7407bc26>阅读 2477</span></div></div></div><h1 data-v-7407bc26>解析一下阿里出品的泰山版Java开发手册</h1><div data-id="5ea632e46fb9a03c8e5fb2c5" itemprop="articleBody" data-v-7407bc26><p>说起华山，我就想起岳不群，不，令狐冲；说起泰山，我就想起司马迁，他的那句名言“人总有一死，或重于泰山，或轻于鸿毛”，真的发人深省啊。这就意味着，阿里出品的泰山版 Java 开发手册，是迄今为止最重量级的。</p><p>华山版是上个版本，啥时候更新的呢？2019 年 06 月 13 号，距离现在 10 个月了，时间也不短了，是时候更新了。</p><p>新版都更新了哪些内容呢？可以从官方的版本历史中看得出来。</p><h3 data-id="heading-0">01、发布错误码统一解决方案</h3><p></p><figure><img data-src="https://user-gold-cdn.xitu.io/2020/4/27/171b934da051adc1?imageView2/0/w/1280/h/960/ignore-error/1" data-width="674" data-height="266" src="https://user-gold-cdn.xitu.io/2020/4/27/171b934da051adc1?imageView2/0/w/1280/h/960/ignore-error/1"><figcaption></figcaption></figure><p></p><p>错误码用来干嘛呢？答案是异常日志，方便我们快速知晓错误来源，判断是谁那出的问题。上图中 A 表示错误来源于用户；还有 B 级的，表示错误来源于当前系统；C 级的，表示错误来源于第三方服务，比如 CDN 服务器。</p><p>这个解决方案还是值得借鉴的，很多成熟的系统都在使用错误码，如果你对接过微信支付的话，应该对错误码不会感到陌生。看到错误码，然后在手册中搜索一下，就能快速知晓错误的类型，还是很不错的。</p><h3 data-id="heading-1">02、新增 34 条新的规约</h3><p>34 条太多了，我就挑几个重要的拉出来说一说吧。</p><p><strong>1）日期时间</strong></p><p>还记得上次技术圈的刷屏事件吧？就是那个 YYYY 和 yyyy 造成的问题。大写的 Y 表示的是当天所在的这一周是属于哪个年份的，小写的 y 表示的是当天所在的年份，差别还是挺大的。你品，你细品。</p><p>还有，大写的 M 和 小写的 m 是不同的，大写的 H 和小写的 h 也是不同的。</p><p></p><figure><img data-src="https://user-gold-cdn.xitu.io/2020/4/27/171b934da090dd94?imageView2/0/w/1280/h/960/ignore-error/1" data-width="230" data-height="119" src="https://user-gold-cdn.xitu.io/2020/4/27/171b934da090dd94?imageView2/0/w/1280/h/960/ignore-error/1"><figcaption></figcaption></figure><p></p><p>另外，像获取当前毫秒数应该使用 <code>System.currentTimeMillis()</code>，而不是 <code>new Date().getTime()</code>，这些细致的规约，都应该牢记在心中，不要去犯这些低级的错误。</p><p><strong>2）三目运算的 NPE 问题</strong></p><p>说实话，这个问题我之前从来没有注意，这次看到了，就一起来学习一下。先来看下面这段代码：</p><pre><code lang="java"><span>public</span> <span><span>class</span> <span>TestCondition</span> </span>{<span><span>public</span> <span>static</span> <span>void</span> <span>main</span><span>(String[] args)</span> </span>{Integer a = <span>1</span>;Integer b = <span>2</span>;Integer c = <span>null</span>;Boolean flag = <span>false</span>;Integer result = flag ? a * b : c;}}<span>复制代码</span></code></pre><p>条件 <code>a * b</code> 属于算术运算，它俩相乘后的结果是一个 int 类型，这就会导致 c 这个 Integer 类型自动拆箱，由于值为 null，就抛出了以下错误：</p><pre><code lang="bash">Exception <span>in</span> thread <span>"main"</span> java.lang.NullPointerExceptionat com.cmower.mkyong.TestCondition.main(TestCondition.java:9)<span>复制代码</span></code></pre><p>那可能你会感到好奇，为什么两个 Integer 类型的变量相乘后会是一个 int 类型呢，这主要是由编译器决定的，它就是这么设计的，来看一下反编译后的字节码：</p><pre><code lang="java"><span>public</span> <span><span>class</span> <span>TestCondition</span></span>{<span><span>public</span> <span>static</span> <span>void</span> <span>main</span><span>(String args[])</span></span>{Integer a = Integer.valueOf(<span>1</span>);Integer b = Integer.valueOf(<span>2</span>);Integer c = <span>null</span>;Boolean flag = Boolean.valueOf(<span>false</span>);Integer result = Integer.valueOf(flag.booleanValue() ? a.intValue() * b.intValue() : c.intValue());}}<span>复制代码</span></code></pre><p><code>a * b</code> 时发生了自动拆箱，调用了 <code>intValue()</code> 方法，而三元运算的两个表达式的类型必须一致，这就导致 c 也调用了 <code>intValue()</code> 方法，由于 c 本身为 null，那就只能 NPE 了。明白了吧？</p><p><strong>3）Collectors 类的 <code>toMap()</code> 方法</strong></p><p>手册上说，在使用 <code>java.util.stream.Collectors</code> 类的 <code>toMap()</code> 方法转 Map 时，一定要使用含有参数类型为 BinaryOperator，参数名为 mergeFunction 的方法，否则当出现相同 key 值时会抛出 IllegalStateException 异常。</p><p>这段话可能理解上有点难度，那先来看一段代码吧！</p><pre><code lang="java">String[] departments = <span>new</span> String[] {<span>"沉默王二"</span>, <span>"沉默王二"</span>, <span>"沉默王三"</span>};Map&lt;Integer, String&gt; map = Arrays.stream(departments).collect(Collectors.toMap(String::hashCode, str -&gt; str));<span>复制代码</span></code></pre><p>运行这段代码的时候，就会抛出异常，堆栈信息如下所示：</p><pre><code lang="bash">Exception <span>in</span> thread <span>"main"</span> java.lang.IllegalStateException: Duplicate key 867758096 (attempted merging values 沉默王二 and 沉默王二)at java.base/java.util.stream.Collectors.duplicateKeyException(Collectors.java:133)at java.base/java.util.stream.Collectors.lambda<span>$uniqKeysMapAccumulator</span><span>$1</span>(Collectors.java:180)<span>复制代码</span></code></pre><p>key 重复了，因为两个“沉默王二”的 hashCode 相同，那这时候的解决办法呢？</p><pre><code lang="java">String[] departments = <span>new</span> String[] {<span>"沉默王二"</span>, <span>"沉默王二"</span>, <span>"沉默王三"</span>};Map&lt;Integer, String&gt; map = Arrays.stream(departments).collect(Collectors.toMap(String::hashCode, str -&gt; str, (v1, v2) -&gt; v2));<span>复制代码</span></code></pre><p>多加个参数 <code>(v1, v2) -&gt; v2</code>，也就是重复的时候选一个。来看看此时调用的 <code>toMap()</code> 方法吧。</p><pre><code lang="java"><span>public</span> <span>static</span> &lt;T, K, U&gt;Collector&lt;T, ?, Map&lt;K,U&gt;&gt; toMap(Function&lt;? <span>super</span> T, ? extends K&gt; keyMapper,Function&lt;? <span>super</span> T, ? extends U&gt; valueMapper,BinaryOperator&lt;U&gt; mergeFunction) {<span>return</span> toMap(keyMapper, valueMapper, mergeFunction, HashMap::<span>new</span>);}<span>复制代码</span></code></pre><p>BinaryOperator 和 mergeFunction 是不是出现了？</p><h3 data-id="heading-2">03、修改描述 90 处</h3><p>手册上说，比如，阻塞等待锁、建表的小数类型等描述有修改，我特么花了半个小时也没有找出来和上一个版本之间的差别。</p><p></p><figure><img alt="泰山版" data-src="https://user-gold-cdn.xitu.io/2020/4/27/171b934da1361fe4?imageView2/0/w/1280/h/960/ignore-error/1" data-width="699" data-height="94" src="https://user-gold-cdn.xitu.io/2020/4/27/171b934da1361fe4?imageView2/0/w/1280/h/960/ignore-error/1"><figcaption></figcaption></figure><p></p><p></p><figure><img alt="华山版" data-src="https://user-gold-cdn.xitu.io/2020/4/27/171b934da121e2e3?imageView2/0/w/1280/h/960/ignore-error/1" data-width="692" data-height="94" src="https://user-gold-cdn.xitu.io/2020/4/27/171b934da121e2e3?imageView2/0/w/1280/h/960/ignore-error/1"><figcaption></figcaption></figure><p></p><p>不知道是不是手册的小编在瞎说，你要是能发现差别，告诉我一声。</p><h3 data-id="heading-3">04、完善若干处示例</h3><p>比如说 SQL 语句栏目里的 ISNULL 的示例，确实比华山版追加了一个更详细的反例，见下图。</p><p></p><figure><img data-src="https://user-gold-cdn.xitu.io/2020/4/27/171b934da1e85a84?imageView2/0/w/1280/h/960/ignore-error/1" data-width="699" data-height="248" src="https://user-gold-cdn.xitu.io/2020/4/27/171b934da1e85a84?imageView2/0/w/1280/h/960/ignore-error/1"><figcaption></figcaption></figure><p></p><p>但说实话，这段反例的描述我看了至少六遍才搞懂是什么意思。首先，不要在 null 前换行，影响阅读性，这倒是真的；其次呢，不要使用 <code>column is null</code> 进行判空，使用 <code>ISNULL(column)</code> 判空，效率更高，也不会出现换行的情况。</p><pre><code lang="sql"><span>select</span> * <span>from</span> cms_subject <span>where</span> <span>column</span> <span>is</span> <span>null</span> <span>and</span>column1 <span>is</span> <span>not</span> <span>null</span>;<span>select</span> * <span>from</span> cms_subject <span>where</span> <span>ISNULL</span>(<span>column</span>) <span>and</span>column1 <span>is</span> <span>not</span> <span>null</span>;<span>复制代码</span></code></pre><h3 data-id="heading-4">05、最后</h3><p>2016 年 12 月份，阿里首次向业界开放了这份《Java 开发手册》，到泰山版发布，已经过去了 3 年多时间了，这份手册也在全球 Java 开发者共同的努力下，成为业界普遍遵循的开发规范。这份手册包含的知识点非常全面，七大维度编程规约、异常日志、单元测试、安全规约、MySQL数据库、工程规约、设计规约都有罗列。</p><p>如果你想成为一名优秀的 Java 工程师，那么这份手册上的内容几乎是必须要掌握的。如果你手上还没有这份手册，可以微信搜索「<strong>沉默王二</strong>」回复「<strong>手册</strong>」免费获取。已经有了的小伙伴，请忽略。最后，我衷心地祝福你，希望你能学有所成，to be better，奥利给！</p></div></article>
