### ISSUE TITLE
一次线上服务高 CPU 占用优化实践

### ISSUE THREAD

**Issue by yf2008** [yf2008/duty-machine#57]
https://juejin.im/post/5eb239c95188256d882ee619

**Comment by yf2008** [comment]
一次线上服务高 CPU 占用优化实践 by 2020年05月06日阅读 476
------
<article itemscope="itemscope" itemtype="http://schema.org/Article" data-v-7407bc26><meta itemprop="url" content="https://juejin.im/post/5eb239c95188256d882ee619"><meta itemprop="headline" content="一次线上服务高 CPU 占用优化实践"><meta itemprop="keywords" content="架构,性能优化"><meta itemprop="datePublished" content="2020-05-06T04:16:02.468Z"><meta itemprop="image" content="https://b-gold-cdn.xitu.io/icon/icon-128.png"><div itemprop="author" itemscope="itemscope" itemtype="http://schema.org/Person"><meta itemprop="name" content="挖坑的张师傅"><meta itemprop="url" content="https://juejin.im/user/57a14cc3c4c971005af0d8df"></div><div itemprop="publisher" itemscope="itemscope" itemtype="http://schema.org/Organization"><meta itemprop="name" content="掘金"><div itemprop="logo" itemscope="itemscope" itemtype="https://schema.org/ImageObject"><meta itemprop="url" content="https://b-gold-cdn.xitu.io/icon/icon-white-180.png"><meta itemprop="width" content="180"><meta itemprop="height" content="180"></div></div><div data-v-7407bc26><a href="/post/5eb239c95188256d882ee619" target="_blank" rel="" data-v-7407bc26><div data-src="https://b-gold-cdn.xitu.io/v3/static/img/default-avatar.e30559a.svg" data-v-292b3648 data-v-11331c20 data-v-7407bc26></div></a><div data-v-7407bc26><a href="/post/5eb239c95188256d882ee619" target="_blank" rel="" data-v-44e95489 data-v-7407bc26></a><div data-v-7407bc26><time datetime="2020-05-06T04:16:02.468Z" title="Wed May 06 2020 12:16:02 GMT+0800 (China Standard Time)" data-v-7407bc26>2020年05月06日</time><span data-v-7407bc26>阅读 476</span></div></div></div><h1 data-v-7407bc26>一次线上服务高 CPU 占用优化实践</h1><div data-id="5eb23a02f265da7c026bdd36" itemprop="articleBody" data-v-7407bc26><p>线上有一个非常繁忙的服务的 JVM 进程 CPU 经常跑到 100% 以上，下面写了一下排查的过程。通过阅读这篇文章你会了解到下面这些知识。</p><ul><li>Java 程序 CPU 占用高的排查思路</li><li>可能造成线上服务大量异常的 log4j 假异步</li><li>Kafka 异步发送的优化</li><li>On-CPU 火焰图的原理和解读</li><li>使用 Trie 前缀树来优化 Spring 的路径匹配</li></ul><h2 data-id="heading-0">开始尝试</h2><p>JVM CPU 占用高，第一反应是找出 CPU 占用最高的线程，看这个线程在执行什么，使用 top 命令可以查看进程中所有线程占用的 CPU 情况，命令如下所示。</p><pre><code lang="bash">top -Hp you_pid<span>复制代码</span></code></pre><p>输出如下：</p><pre><code lang="bash">  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND48 root      20   0 30.367g 2.636g  12940 S  12.7  2.9  36:15.18 java2365 root      20   0 30.367g 2.636g  12940 R  1.3  2.9   2:33.64 java2380 root      20   0 30.367g 2.636g  12940 S  1.3  2.9   2:33.10 java2381 root      20   0 30.367g 2.636g  12940 S  1.3  2.9   2:33.41 java10079 root      20   0 30.367g 2.636g  12940 S  1.3  2.9   0:30.73 java10 root      20   0 30.367g 2.636g  12940 S  1.0  2.9   4:08.54 java11 root      20   0 30.367g 2.636g  12940 S  1.0  2.9   4:08.55 java92 root      20   0 30.367g 2.636g  12940 S  1.0  2.9   2:53.71 java681 root      20   0 30.367g 2.636g  12940 S  1.0  2.9   2:52.56 java683 root      20   0 30.367g 2.636g  12940 S  1.0  2.9   2:56.81 java690 root      20   0 30.367g 2.636g  12940 S  1.0  2.9   3:34.24 java<span>复制代码</span></code></pre><p>可以看到占用 CPU 最高的线程 PID 为 48(0x30)，使用 jstack 输出当前线程堆栈，然后 grep 一下 0x30，如下所示。</p><pre><code lang="bash">jstack 1 | grep -A 10 <span>"0x30 "</span><span>复制代码</span></code></pre><p>输出结果如下。</p><pre><code lang="bash"><span>"kafka-producer-network-thread | producer-1"</span> <span>#35 daemon prio=5 os_prio=0 tid=0x00007f9ac4fc7000 nid=0x30 runnable [0x00007f9ac9b88000]</span>java.lang.Thread.State: RUNNABLEat sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)- locked &lt;0x0000000094ef70c8&gt; (a sun.nio.ch.Util<span>$3</span>)- locked &lt;0x0000000094ef70e0&gt; (a java.util.Collections<span>$UnmodifiableSet</span>)- locked &lt;0x000000009642bbb8&gt; (a sun.nio.ch.EPollSelectorImpl)at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)at org.apache.kafka.common.network.Selector.select(Selector.java:686)<span>复制代码</span></code></pre><p>可以看到这是一个 kafka 的发送线程。我们的日志打印是使用 log4j2 的 kafka 插件将日志文件写入到 kafka，日志写入量非常大。接下来先来优化这个 kafka 发送线程的 CPU 占用。</p><h2 data-id="heading-1">Log4j2 下 KafkaAppender 优化</h2><p>KafkaAppender 中封装了 KafkaProducer，经过测试与 KafkaProducer 发送频率有很大关系的有这几个参数 <code>batch.size</code>、<code>linger.ms</code>。接下来看看这里几个参数有什么实际的作用。</p><h4 data-id="heading-2">linger.ms</h4><p>KafkaProducer 在 batch 缓冲区满或者 linger.ms 时间到达时，会讲消息发送出去。linger.ms 用来指定发送端在 batch 缓冲池被填满之前最多等待多长时间，相当于 TCP 协议的 Nagle 算法。</p><p>这个值默认为 0，只要有数据 Sender 线程就会一直发，不会等待，就算 batch 缓冲区只有一条数据也会立即发送。这样消息发送的延迟确实很低，但是吞吐量会变得很差。</p><p>设置一个大于 0 的值，可以让发送端在缓冲区没有满的情况下等待一段时间，累积 linger.ms 时间的数据一起发送。这样可以减少请求的数量，避免频繁发送太多小包，不会立即发送数据。这样增加了消息的时延（latency），但是提高了吞吐量（throughput）。</p><h4 data-id="heading-3">batch.size</h4><p>KafkaProducer 在发送多条消息时，会把发往同一个 partition 的的消息当做一个 batch 批量发送。</p><p>batch.size 用于指定批量发送缓存内存区域的大小，注意这里不是条数，默认值是 16384（16KB）</p><p>当 batch 缓冲区满，缓冲区中所有的消息会被发送出去。这并不意味着 KafkaProducer 会等到 batch 满才会发，不然只有一条消息时，消息就一直发不出去了。<code>linger.ms</code> 和 <code>batch.size</code> 都会影响 KafkaProducer 的发送行为。</p><p>batch.size 值设置太小会降低吞吐量，太大会浪费内存。</p><p>我们线上的配置这两个值都没配置，会按 linger.ms=0，batch.size 为 16KB 的配置运行，因为日志产生的非常频繁，Sender 线程几乎不会闲下来，一直在处理发送数据包。</p><h2 data-id="heading-4">log4j2 的异步 Appender 潜在的坑</h2><p>在做 Kafka 发送端的参数调整之前有一个风险点，log4j2 的异步 Appender 潜在的坑需要提前避免，否则会造成线上业务接口的大量超时。</p><p>log4j2 的异步 Appender 原理上是在本地利用了本地的一个 ArrayBlockingQueue 存储应用层发过来的消息，这个 queue 的大小默认值在 2.7 版本的 log4j2 中是 128，在高版本中，这个值已经被调为了 1024。如果 KafkaAppender 处理的比较慢，很快这个队列就填满，如下图所示。</p><p></p><figure><img data-src="https://user-gold-cdn.xitu.io/2020/5/6/171e83176fbbcde5?imageView2/0/w/1280/h/960/ignore-error/1" data-width="1280" data-height="291" src="https://user-gold-cdn.xitu.io/2020/5/6/171e83176fbbcde5?imageView2/0/w/1280/h/960/ignore-error/1"><figcaption></figcaption></figure><p></p><p>填满以后就涉及到是 blocking 等待，还是丢弃后面加入的日志的问题，比较坑的是 log4j2 的默认配置是 DefaultAsyncQueueFullPolicy，这个策略是同步阻塞等待当前线程。我们可以选择将这个值设置为丢弃，以保证不管底层的日志写入慢不慢，都不能影响上层的业务接口，大不了就丢弃部分日志。log4j 提供了配置项，将系统属性 log4j2.AsyncQueueFullPolicy 设置为 Discard 即可。</p><p>这还没完，设置了队列满的策略为 Discard 后，log4j 默认只会舍弃 INFO 及以下级别的日志。如果系统大量产生 WARN、ERROR 级别的日志，就算策略是 Discard 还是会造成阻塞上游线程，需要将 log4j2.DiscardThreshold 设置为 ERROR 或者 FATAL。</p><p>修改了 KafkaProducer 和 log4j 的参数以后，kafka 发送线程的 CPU 占用降低到了 5% 以下，整体的 CPU 负载依旧是比较高的，接下来继续排查。</p><h2 data-id="heading-5">万能的火焰图</h2><p>一开始本来想用 perf、dtrace、systemtap 等工具来生成火焰图，无奈在 Docker 容器中没有 privileged 权限，我一一尝试了都无法运行上面的所有命令，好在是 Arthas 提供了火焰图生成的命令 profiler，它的原理是利用 async-profiler 对应用采样，生成火焰图。</p><p>使用 arthas Attach 上 JVM 进程以后，使用 profiler start 开始进行采样，运行一段时间后执行 profiler stop 就可以生成火焰图 svg 了，部分如下图所示。</p><figure><img data-src="https://user-gold-cdn.xitu.io/2020/5/6/171e8317739f4df1?imageView2/0/w/1280/h/960/ignore-error/1" data-width="1280" data-height="584" src="https://user-gold-cdn.xitu.io/2020/5/6/171e8317739f4df1?imageView2/0/w/1280/h/960/ignore-error/1"><figcaption></figcaption></figure><p></p><p>火焰图有几个特征：</p><ul><li>每个框代表栈里的一个函数；</li><li>Y 轴表示函数调用栈的深度，下层函数是上层函数的父调用。调用栈越深，火焰越高；</li><li>X 轴不是表示时间的流逝，而是表示抽样数，一个函数在 X 轴的宽度越宽，表示它在采样中被抽到的次数越多，执行时间越长。</li></ul><p>从上面的图可以看到 kafka 和 Spring 函数执行的 CPU 占用最多，kafka 的问题上面的内容可以优化，接下来我们来看 Spring 函数相关调用栈。</p><h3 data-id="heading-6">log4j 行号计算的代价</h3><p>把 svg 放大，可以看到有一个顶一直都平很高，函数是 Log4jLogEvent.calcLocation，也就是 log4j 生成日志打印行数的计算的地方，如下图所示。</p><figure><img data-src="https://user-gold-cdn.xitu.io/2020/5/6/171e831779274df6?imageView2/0/w/1280/h/960/ignore-error/1" data-width="1280" data-height="617" src="https://user-gold-cdn.xitu.io/2020/5/6/171e831779274df6?imageView2/0/w/1280/h/960/ignore-error/1"><figcaption></figcaption></figure><p></p><p>计算行号的原理实际上是通过获取当前调用堆栈来实现的，这个计算性能很差，具体有多慢，网上有很多 benchmark 的例子可以实测一下。</p><p>我们把 log4j 的行号输出关掉，CPU 占用又小了一点点，这个平顶的调用也不见了。</p><h2 data-id="heading-7">使用 Trie 前缀树来优化 Spring 本身的性能问题</h2><p>继续分析占用高函数调用。因为历史的原因，我们在 url 设计上没有能提前考虑将不需要走鉴权的 url 放在同一个前缀路径下，导致 interceptor 的 exclude-mapping 配置有一百多个，如下所示。</p><pre><code lang="xml"><span>&lt;<span>mvc:interceptors</span>&gt;</span><span>&lt;<span>mvc:interceptor</span>&gt;</span><span>&lt;<span>mvc:mapping</span> <span>path</span>=<span>"/**"</span>/&gt;</span><span>&lt;<span>mvc:exclude-mapping</span> <span>path</span>=<span>"/login"</span>/&gt;</span><span>&lt;<span>mvc:exclude-mapping</span> <span>path</span>=<span>"/*/login"</span>/&gt;</span><span>&lt;<span>mvc:exclude-mapping</span> <span>path</span>=<span>"/*/activity/teacher"</span>/&gt;</span><span>&lt;<span>mvc:exclude-mapping</span> <span>path</span>=<span>"/masaike/dynamic/**"</span>/&gt;</span>...下面还有一百多个这样的 exclude...<span>&lt;<span>mvc:exclude-mapping</span> <span>path</span>=<span>"/masaike/aaaa/**"</span>/&gt;</span><span>&lt;<span>mvc:exclude-mapping</span> <span>path</span>=<span>"/masaike/**/hello"</span>/&gt;</span><span>&lt;<span>bean</span> <span>class</span>=<span>"com.masaike.AuthenticationHandlerInterceptor"</span>/&gt;</span><span>&lt;/<span>mvc:interceptor</span>&gt;</span><span>&lt;/<span>mvc:interceptors</span>&gt;</span><span>复制代码</span></code></pre><p>Spring MVC 处理这一段的逻辑在 <code>org.springframework.web.servlet.handler.MappedInterceptor</code></p><figure><img data-src="https://user-gold-cdn.xitu.io/2020/5/6/171e83178b3b9f6f?imageView2/0/w/1280/h/960/ignore-error/1" data-width="1280" data-height="786" src="https://user-gold-cdn.xitu.io/2020/5/6/171e83178b3b9f6f?imageView2/0/w/1280/h/960/ignore-error/1"><figcaption></figcaption></figure><p></p><ul><li>对于一个需要鉴权的接口，它会遍历整个 excludePatterns 列表</li><li>对于一个的确不需要鉴权的接口，for 循环会在中间 break。最坏的情况下，也需要遍历完所有的 excludePatterns 列表</li></ul><p>这样效率太低了，我们完全可以优化这段逻辑，使用 trie 树来实现路径的匹配，与普通 trie 树有区别的地方在于，这里的 trie 树需要能支持中间带通配符 <code>*</code> 和 <code>**</code> 的格式。</p><p>假如我们有下面这些路径：</p><pre><code lang="bash">  <span>"/api/*/login"</span>, <span>"/wildcard/**"</span>, <span>"/wildcard/**/hello"</span>, <span>"/v2/hello/"</span>, <span>"/v2/user/info/"</span>, <span>"/v2/user/feed/"</span>, <span>"/v2/user/feed2/"</span><span>复制代码</span></code></pre><p>生成的 trie 树如下所示。</p><pre><code lang="bash">.└──api└──*└──login└──v2└──hello└──user└──feed└──feed2└──info└──wildcard└──**<span>复制代码</span></code></pre><p>实现倒是非常简单，每个 node 节点都有包含一个 map 表示的 child 列表，这样在查找的时候就非常快。</p><pre><code lang="bash">/*** @author Arthur.Zhang (zhangya@imlizhi.com)* 用于匹配 /a/b/c, *, ** 这种格式的前缀匹配* 参考了 ZooKeeper 和 lucene 的 trie 实现*/public class PathTrie {private Node root = new Node(emptyList(), null);public <span><span>PathTrie</span></span>() {}public void insert(String path, String obj) {List&lt;String&gt; parts = getPathSegments(path);insert(parts, obj);}public void insert(List&lt;String&gt; parts, String o) {<span>if</span> (parts.isEmpty()) {root.obj = o;<span>return</span>;}root.insert(parts, o);}private static List&lt;String&gt; getPathSegments(String path) {<span>return</span> Splitter.on(<span>'/'</span>).splitToList(path).stream().filter(it -&gt; !it.isEmpty()).collect(Collectors.toList());}public boolean existsPath(String path) {<span>return</span> root.exists(getPathSegments(path), 0);}public void <span><span>dump</span></span>() {<span>if</span> (root != null) root.dump();}private static class Node {String name;Map&lt;String, Node&gt; children;String obj; // 标识是否是叶子节点Node(List&lt;String&gt; path, String obj) {<span>if</span> (path.isEmpty()) {this.obj = obj;<span>return</span>;}name = path.get(0);}private synchronized void insert(List&lt;String&gt; parts, String o) {String part = parts.get(0);Node matchedChild;// 如果是 **，后面的路径节点不用再插入了<span>if</span> (<span>"**"</span>.equals(name)) {<span>return</span>;}<span>if</span> (children == null) children = new ConcurrentHashMap&lt;&gt;();matchedChild = children.get(part);<span>if</span> (matchedChild == null) {matchedChild = new Node(parts, o);children.put(part, matchedChild);}// 移除已处理的parts.remove(0);<span>if</span> (parts.isEmpty()) { // 如果已经到底，将最后一个 child 的 obj 赋值matchedChild.obj = o;} <span>else</span> {matchedChild.insert(parts, o); //还没有到底，继续递归插入}}/*** @param pathSegments 路径分割以后的 word 列表，比如 /a/b/c -&gt; <span>'a'</span> , <span>'b'</span> , <span>'c'</span>* @param level        当前路径遍历的 level 深度，比如 /a/b/c -&gt; 0=<span>'a'</span> 1=<span>'b'</span> 2=<span>'c'</span>*/public boolean exists(List&lt;String&gt; pathSegments, int level) {// 如果已经把传入的 path 遍历完了<span>if</span> (pathSegments.size() &lt; level + 1) {// 如果当前 trie 树不是叶子节点<span>if</span> (obj == null) {// 获取叶子节点是否包含 **，如果包含的话，则匹配到Node n = children.get(<span>"**"</span>);<span>if</span> (n != null) {<span>return</span> <span>true</span>;}}<span>return</span> obj != null;}<span>if</span> (children == null) {<span>return</span> <span>false</span>;}String pathSegment = pathSegments.get(level);// 1、首先找绝对匹配的Node n = children.get(pathSegment);// 2、如果不存在，则找是否包含 * 的<span>if</span> (n == null) {n = children.get(<span>"*"</span>);}// 3、如果还不存在，则找是否包含 ** 的<span>if</span> (n == null) {n = children.get(<span>"**"</span>);<span>if</span> (n != null) {<span>return</span> <span>true</span>;}}// 4、如果这些都没有找到，则返回 <span>false</span><span>if</span> (n == null) {<span>return</span> <span>false</span>;}// 5、如果找到了一个 node，则继续递归查找<span>return</span> n.exists(pathSegments, level + 1);}@Overridepublic String <span><span>toString</span></span>() {<span>return</span> <span>"Node{"</span> +<span>"name='"</span> + name + <span>'\'</span><span>' +", children=" + children +'</span>}<span>';}/*** 使用类似 tree 命令的输出格式打印这棵前缀数* .* └──api* 	└──** 		└──login* └──v2* 	└──hello* 	└──user* 		└──feed* 		└──feed2* 		└──info* └──wildcard* 	    └──***/public void dump() {dump(0);}public void dump(int level) {if (level == 0) {System.out.println(".");} else {StringBuilder sb = new StringBuilder();for (int i = 0; i &lt; level - 1; i++) {sb.append("\t");}sb.append("└──").append(name);System.out.println(sb.toString());}if (children != null &amp;&amp; !children.isEmpty()) {for (Map.Entry&lt;String, Node&gt; item : children.entrySet()) {item.getValue().dump(level + 1);}}}}}</span><span>复制代码</span></code></pre><p>采用 Trie 的实现之后，平均的 CPU 占比消耗降低了 5% 左右。</p><h2 data-id="heading-8">小结</h2><p>整体优化以后，高峰期间的 CPU 占用从 100% 左右下降到了 35%，效果还是比较明显的。</p><p>性能优化是一个全栈的工程，能发现问题就已经解决了一大半了。另外光会命令是不够的，理解底层原理才能真正的有的放矢，发现问题的核心所在。</p><p>有问题可以扫描下面的二维码关注我的公众号到联系我。</p><p></p><figure><img data-src="https://user-gold-cdn.xitu.io/2019/9/9/16d1410666ba596a?imageView2/0/w/1280/h/960/ignore-error/1" data-width="800" data-height="600" src="https://user-gold-cdn.xitu.io/2019/9/9/16d1410666ba596a?imageView2/0/w/1280/h/960/ignore-error/1"><figcaption></figcaption></figure><p></p></div></article>
